language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
  - $HOME/.gradle

install:
  # If the build targets Java 7, we need to temporarily switch to Java 9 to
  # install the Gradle wrapper and to avoid an InvalidKeyException
  - if [[ $JAVA_HOME =~ "java-7" ]]; then
      jdk_switcher use oraclejdk9;
      ./gradlew tasks;
      jdk_switcher use openjdk7;
    fi
